### ISSUE TITLE
Update CodeSniffer standard for 2.0

### ISSUE THREAD

**Issue by linc** [vanilla/addons#282]
See "Removal of the Comment Parser" here: https://www.squizlabs.com/php-codesniffer/2.0.0a1-released

```
[linc@derby community:master]# phpcs applications/addons/
PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Class PHP_CodeSniffer_CommentParser_ClassCommentParser not found' in /git/addons/standards/Vanilla/Sniffs/Commenting/ClassCommentSniff.php:17
Stack trace:
#0 /usr/local/Cellar/php-code-sniffer/2.4.0/CodeSniffer.php(1324): include_once()
#1 /usr/local/Cellar/php-code-sniffer/2.4.0/CodeSniffer.php(560): PHP_CodeSniffer->registerSniffs(Array, Array)
#2 /usr/local/Cellar/php-code-sniffer/2.4.0/CodeSniffer/CLI.php(822): PHP_CodeSniffer->initStandard(Array, Array)
#3 /usr/local/Cellar/php-code-sniffer/2.4.0/CodeSniffer/CLI.php(95): PHP_CodeSniffer_CLI->process()
#4 /usr/local/Cellar/php-code-sniffer/2.4.0/scripts/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in /git/addons/standards/Vanilla/Sniffs/Commenting/ClassCommentSniff.php on line 17

Fatal error: Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Class PHP_CodeSniffer_CommentParser_ClassCommentParser not found' in /git/addons/standards/Vanilla/Sniffs/Commenting/ClassCommentSniff.php on line 17

PHP_CodeSniffer_Exception: Class PHP_CodeSniffer_CommentParser_ClassCommentParser not found in /git/addons/standards/Vanilla/Sniffs/Commenting/ClassCommentSniff.php on line 17

Call Stack:
    0.0004     241272   1. {main}() /usr/local/Cellar/php-code-sniffer/2.4.0/scripts/phpcs:0
    0.0084    1770768   2. PHP_CodeSniffer_CLI->runphpcs() /usr/local/Cellar/php-code-sniffer/2.4.0/scripts/phpcs:25
    0.0088    1836344   3. PHP_CodeSniffer_CLI->process() /usr/local/Cellar/php-code-sniffer/2.4.0/CodeSniffer/CLI.php:95
    0.0092    1854912   4. PHP_CodeSniffer->initStandard() /usr/local/Cellar/php-code-sniffer/2.4.0/CodeSniffer/CLI.php:822
    0.0184    1913712   5. PHP_CodeSniffer->registerSniffs() /usr/local/Cellar/php-code-sniffer/2.4.0/CodeSniffer.php:560
    0.0193    2073320   6. include_once('/git/addons/standards/Vanilla/Sniffs/Commenting/ClassCommentSniff.php') /usr/local/Cellar/php-code-sniffer/2.4.0/CodeSniffer.php:1324
```

**Comment by Daazku** [comment]
Moved to the proper repo.

**Comment by R-J** [comment]
Could you please exclude the old standards from this repo and maybe also link to the correct one?[ I had some troubles](https://github.com/vanilla/standards/pull/2) because I've lost track where to look.
